-- Applied on 2026-02-15 to fix product creation errors
-- 1. Add auto-incrementing ID to products table (starting from 9 as max id was 8)
ALTER TABLE products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 9);

-- 2. Add default values for rating and reviews (fixes not-null constraint error on creation)
ALTER TABLE products ALTER COLUMN rating SET DEFAULT 0;
ALTER TABLE products ALTER COLUMN reviews SET DEFAULT 0;
