export const products = [
    {
        id: 1,
        title: "Rosa Clásica Bordada",
        category: "Flores y Naturaleza",
        price: 4.99,
        oldPrice: 7.99,
        imageColor: "linear-gradient(135deg, #fecdd3, #fda4af)",
        badge: "Nuevo",
        size: "10×10 cm",
        stitches: "12,450",
        formats: "DST / PES",
        rating: 4.8,
        reviews: 124,
        description: "Diseño de rosa clásica con pétalos detallados y hojas verdes. Ideal para camisetas, bolsos, gorras y cualquier proyecto de bordado.",
    },
    {
        id: 2,
        title: "Mariposa Monarca",
        category: "Animales",
        price: 5.99,
        oldPrice: null,
        imageColor: "linear-gradient(135deg, #fed7aa, #fdba74)",
        badge: "Popular",
        size: "8×6 cm",
        stitches: "9,800",
        formats: "DST / PES",
        rating: 4.9,
        reviews: 85,
        description: "Hermosa mariposa monarca con detalles realistas en las alas. Perfecta para decorar prendas primaverales.",
    },
    {
        id: 3,
        title: "Letra Monograma A",
        category: "Letras y Monogramas",
        price: 3.49,
        oldPrice: 4.99,
        imageColor: "linear-gradient(135deg, #dbeafe, #93c5fd)",
        badge: "-30%",
        badgeColor: "green",
        size: "5×5 cm",
        stitches: "6,200",
        formats: "DST / PES",
        rating: 4.7,
        reviews: 42,
        description: "Letra A estilizada con adornos florales sutiles. Ideal para personalizar toallas o pañuelos.",
    },
    {
        id: 4,
        title: "Unicornio Kawaii",
        category: "Infantil",
        price: 6.49,
        oldPrice: null,
        imageColor: "linear-gradient(135deg, #e9d5ff, #c4b5fd)",
        badge: "Nuevo",
        size: "12×10 cm",
        stitches: "15,300",
        formats: "DST / PES",
        rating: 5.0,
        reviews: 60,
        description: "Tierno unicornio estilo kawaii con melena arcoíris. El favorito de los más pequeños.",
    },
    {
        id: 5,
        title: "Escudo Fútbol",
        category: "Deportes",
        price: 7.99,
        oldPrice: null,
        imageColor: "linear-gradient(135deg, #d1fae5, #6ee7b7)",
        badge: null,
        size: "8×8 cm",
        stitches: "18,000",
        formats: "DST / PES",
        rating: 4.6,
        reviews: 30,
        description: "Escudo genérico de fútbol, ideal para equipaciones deportivas o bolsas de deporte.",
    },
    {
        id: 6,
        title: "Mandala Geométrico",
        category: "Geométricos",
        price: 5.49,
        oldPrice: null,
        imageColor: "linear-gradient(135deg, #fef3c7, #fde68a)",
        badge: null,
        size: "15×15 cm",
        stitches: "22,000",
        formats: "DST / PES",
        rating: 4.9,
        reviews: 150,
        description: "Complejo diseño de mandala geométrico. Requiere estabilizador firme debido a la densidad de puntadas.",
    },
    {
        id: 7,
        title: "Girasol Dorado",
        category: "Flores y Naturaleza",
        price: 4.49,
        oldPrice: null,
        imageColor: "linear-gradient(135deg, #fecdd3, #fb923c)",
        badge: "Nuevo",
        size: "8×8 cm",
        stitches: "10,500",
        formats: "DST / PES",
        rating: 4.8,
        reviews: 95,
        description: "Girasol vibrante que aporta luz a cualquier prenda. Colores cálidos y acabado satinado.",
    },
    {
        id: 8,
        title: "Papá Noel",
        category: "Navidad",
        price: 4.99,
        oldPrice: null,
        imageColor: "linear-gradient(135deg, #fce7f3, #f9a8d4)",
        badge: null,
        size: "10×12 cm",
        stitches: "14,800",
        formats: "DST / PES",
        rating: 4.7,
        reviews: 200,
        description: "Clásico diseño de Papá Noel para la temporada festiva. Ideal para calcetines de navidad y suéteres.",
    },
];
