-- Create site_config table if it doesn't exist
CREATE TABLE IF NOT EXISTS site_config (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hero_title TEXT,
    hero_badge TEXT,
    hero_description TEXT,
    hero_image_url TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable RLS
ALTER TABLE site_config ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Public can view site config" 
ON site_config FOR SELECT 
USING (true);

-- Allow admin full access (assuming admin role check or simple auth for now based on project context)
-- Adjusting to match existing admin policies (auth.uid() check usually)
CREATE POLICY "Admins can update site config" 
ON site_config FOR ALL 
USING (auth.role() = 'authenticated'); -- Or more specific admin check if available

-- Insert default row if empty
INSERT INTO site_config (hero_title, hero_badge, hero_description, hero_image_url)
SELECT 
    'Diseños de Bordado Profesionales',
    'Más de 5,000 diseños disponibles',
    'Archivos digitales listos para tu máquina bordadora. Formatos DST, PES, JEF, VP3 y más. Descarga instantánea.',
    NULL
WHERE NOT EXISTS (SELECT 1 FROM site_config);

-- Create storage bucket for site assets if it doesn't exist
INSERT INTO storage.buckets (id, name, public)
SELECT 'site-assets', 'site-assets', true
WHERE NOT EXISTS (SELECT 1 FROM storage.buckets WHERE id = 'site-assets');

-- Storage policies for site-assets
CREATE POLICY "Public Access"
ON storage.objects FOR SELECT
USING ( bucket_id = 'site-assets' );

CREATE POLICY "Admin Upload"
ON storage.objects FOR INSERT
WITH CHECK ( bucket_id = 'site-assets' AND auth.role() = 'authenticated' );

CREATE POLICY "Admin Update"
ON storage.objects FOR UPDATE
USING ( bucket_id = 'site-assets' AND auth.role() = 'authenticated' );

CREATE POLICY "Admin Delete"
ON storage.objects FOR DELETE
USING ( bucket_id = 'site-assets' AND auth.role() = 'authenticated' );
